# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "luminositylabsllc/bento-ubuntu-22.04-arm64"
  config.vm.provision "shell", path: "script.sh"
  config.vm.define "server1" do |server1|
    server1.vm.hostname = "server1"
  end
  config.vm.define "server2" do |server2|
    server2.vm.hostname = "server2"
  end
end
